version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sette-game
    volumes: 
      - ./db-data/:/var/lib/postgres/data
    ports:
      - 5432:5432
  back-end:
    image: node:lts-alpine
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "9000:9000"
# networks:
  # front:
    # driver: overlay
    # attachable: true
  # back:
    # driver: overlay
    # attachable: true